spring.application.name=dao
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.semester.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ?? Spring Security ????


