spring:
  profiles:
    include: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  logging:
    config: classpath:logback-spring.xml
    level:
      root: info
      org.bupt.minisemester: debug

zhipuai:
  api:
    secret-key: "4f477d4825d49561235b85b0df0acc69.RCvVx7rOnKaAmQL1"


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.semester.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ?? Spring Security ????


